export const wrapper: string;
export const thumbnail: string;
export const title: string;
export const publisher: string;
export const name: string;
export const issue: string;
export const info: string;
export const description: string;
export const play: string;